version: '3.7'
services:
  application:
    container_name: nodejs
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - application
    ports:
      - 8989:8989